## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import numpy as np

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(['EIN', 'NAME'], axis=1, inplace=True)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
app_type_count = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace= app_type_count[app_type_count <= 500].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df['CLASSIFICATION'].value_counts()
class_counts.head(30)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = class_counts[class_counts <= 300].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric = pd.get_dummies(application_df)
numeric

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
X = numeric.drop(["IS_SUCCESSFUL"],axis=1)
y = numeric["IS_SUCCESSFUL"]


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [22]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.


#ATTEMPT 2 FOR 75+ ACCURACY

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=8, activation="relu", input_dim=len(X_train_scaled[0])))
# Second hidden layer
nn.add(tf.keras.layers.Dense(units = 16, activation="relu"))
# Third hidden layer
nn.add(tf.keras.layers.Dense(units = 16, activation="relu"))

# Arbitrarly chose 8

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_11 (Dense)            (None, 8)                 360

 dense_12 (Dense)            (None, 16)                144

 dense_13 (Dense)            (None, 16)                272

 dense_14 (Dense)            (None, 1)                 17

=================================================================
Total params: 793 (3.10 KB)
Trainable params: 793 (3.10 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [25]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.


#ATTEMPT 3 FOR 75+ ACCURACY

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=len(X_train_scaled[0])))
# Second hidden layer
nn.add(tf.keras.layers.Dense(units = 8, activation="relu"))
# Third hidden layer
nn.add(tf.keras.layers.Dense(units = 2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_15 (Dense)            (None, 16)                720

 dense_16 (Dense)            (None, 8)                 136

 dense_17 (Dense)            (None, 2)                 18

 dense_18 (Dense)            (None, 1)                 3

=================================================================
Total params: 877 (3.43 KB)
Trainable params: 877 (3.43 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [26]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [27]:
# Train the model
# Got errors with fit_model = nn.fit(X_train_scaled,y_train,epochs=100)
# convert them to arrays as found on Stack overflow
y_train = np.array(y_train)
y_test = np.array(y_test)

fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.6587 - accuracy: 0.6120
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6067 - accuracy: 0.6932
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5926 - accuracy: 0.7042
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5704 - accuracy: 0.7247
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5668 - accuracy: 0.7255
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5655 - accuracy: 0.7257
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5648 - accuracy: 0.7267
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5651 - accuracy: 0.7271
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5638 - accuracy: 0.7270
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5637 - accuracy: 0.7293
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5629 - accuracy: 0.7287
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5633 - accuracy: 0.7287
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5606 - accuracy: 0.7300
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5590 - accuracy: 0.7312
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5586 - accuracy: 0.7320
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5584 - accuracy: 0.7317
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5578 - accuracy: 0.7325
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5573 - accuracy: 0.7324
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5572 - accuracy: 0.7322
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.7326
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5553 - accuracy: 0.7327
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5551 - accuracy: 0.7322
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5549 - accuracy: 0.7324
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5549 - accuracy: 0.7322
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5547 - accuracy: 0.7326
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5545 - accuracy: 0.7329
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5546 - accuracy: 0.7331
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5545 - accuracy: 0.7332
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5544 - accuracy: 0.7333
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5546 - accuracy: 0.7334
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5542 - accuracy: 0.7327
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5543 - accuracy: 0.7333
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5542 - accuracy: 0.7335
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5541 - accuracy: 0.7324
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5540 - accuracy: 0.7329
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5540 - accuracy: 0.7333
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5539 - accuracy: 0.7325
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5539 - accuracy: 0.7335
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5537 - accuracy: 0.7331
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5536 - accuracy: 0.7332
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5532 - accuracy: 0.7334
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5532 - accuracy: 0.7345
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5530 - accuracy: 0.7334
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5531 - accuracy: 0.7332
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5532 - accuracy: 0.7334
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5531 - accuracy: 0.7329
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5528 - accuracy: 0.7332
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5527 - accuracy: 0.7343
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5526 - accuracy: 0.7333
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5529 - accuracy: 0.7333
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5520 - accuracy: 0.7343
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5501 - accuracy: 0.7355
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5498 - accuracy: 0.7356
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5495 - accuracy: 0.7366
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5497 - accuracy: 0.7350
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5491 - accuracy: 0.7361
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5494 - accuracy: 0.7357
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5487 - accuracy: 0.7361
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5488 - accuracy: 0.7356
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7356
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5490 - accuracy: 0.7355
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5487 - accuracy: 0.7353
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5487 - accuracy: 0.7357
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5486 - accuracy: 0.7371
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7360
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7364
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7363
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5486 - accuracy: 0.7367
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5487 - accuracy: 0.7361
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5486 - accuracy: 0.7372
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7372
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7374
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5483 - accuracy: 0.7365
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5483 - accuracy: 0.7370
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7363
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7364
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7357
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7371
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7362
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7368
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7366
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7360
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7358
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7379
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7374
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7370
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7370
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7370
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5476 - accuracy: 0.7377
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7373
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5475 - accuracy: 0.7366
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7370
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7371
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7375
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7372
Epoch 96/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5472 - accuracy: 0.7369
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7378
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7370
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5469 - accuracy: 0.7376
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7375

In [28]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5587 - accuracy: 0.7255 - 371ms/epoch - 1ms/step
Loss: 0.5586735010147095, Accuracy: 0.7254810333251953

In [34]:
# Export our model to HDF5 file
from google.colab import files
nn.save("AlphabetSoupCharity_Optimization.h5")
files.download("AlphabetSoupCharity_Optimization.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(